live_config_reload = true

[window]
opacity = 0.8
decorations = "Transparent"
blur = true

  [window.padding]
  x = 10
  y = 45

[font]
size = 11
normal = {family = "MesloLGS Nerd Font Mono", style = "Regular"}

[colors]
  [colors.primary]
  background = "#0B0C0F"
  foreground = "#F2E9E1"

  [colors.cursor]
  text = "#b877db"
  cursor = "#b877db"

  # Normal colors
  [colors.normal]
  black   = '#0B0C0F'
  red     = '#E95378'
  green   = '#1EA071'
  yellow  = '#F6C177'
  blue    = '#1555A5'
  magenta = '#A347BA'
  cyan    = '#3E8FB0'
  white   = '#edecee'

  # Bright colors
  [colors.bright]
  black   = '#5E5C64'
  red     = '#F09483'
  green   = '#61ffca'
  yellow  = '#EA9D34'
  blue    = '#2A7BDE'
  magenta = '#C061CB'
  cyan    = '#286983'
  white   = '#edecee'


[cursor]
  [cursor.style]
  shape = "Block"
  blinking = "Always"

  [cursor.vi_mode_style]
  shape = "Block"
  blinking = "Always"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]